VariableCount.desc = Counts the Number of Times a Variable is Declared
VariableCount.name = Variable Declaration Count
CastCount.desc = The Number of Times a Cast was Done
CastCount.name = Cast Count
CatAChecks.desc = The Checks for Category A