hLength.desc = Finds the total amount of operands and operators
hLength.name = Halstead Length 
hVocab.desc = Finds the total amount of UNIQUE operands and operators
hVocab.name = Halstead Vocab
hVol.desc = Calculates the program length * log_2 of the program vocabulary
hVol.name = Halstead Volume
hDifficulty.desc = Calculates 0.5 unique operators * total operators / all unique operators
hDifficulty.name = Halstead Difficulty
hEffort.desc = Finds the Difficulty * the Volume of the program
hEffort.name = Halstead Effort
CatBChecks.desc = The Metrics for Category B