CommentCount.desc = Counts the Number of Comments in a Project
CommentCount.name = Comment Count
CommentLineCount.desc = Counts the Lines of Comments
CommentLineCount.name = Comment Line Count
LoopCount.desc = Counts the Number of Loops in a Project
LoopCount.name = Loop Count
OperatorCount.desc = Counts the Number of Operators in a Project
OperatorCount.name = Operator Count
OperandCount.desc = Counts the Number of Operands in a Project
OperandCount.name = Operand Count
ExpressionCount.desc = Counts the Number of Expressions in a Project
ExpressionCount.name = Expression Count
CatAChecks.desc = The Checks for Category A